#!/bin/bash
# are complete exports, so just to track new listens

wait-for-internet -q --timeout 10 || exit 0

evry 1 week -backup_listenbrainz_scrobbles && {
	BACKUP_DIR="$(python3 -m my.utils.backup_to listenbrainz)"
	printlog "listenbrainz:Running listenbrainz export..."
	arctee -r 3 "${BACKUP_DIR}/{utcnow}.json" -- python3 -m listenbrainz_export seanbreckenridge || send-error 'listenbrainz export: failed to backup scrobbles'
}
