#!/usr/bin/env bash
set -o pipefail

# script to setup HPI
# - installs karlicoss/HPI as an editable namespace package,
# - installs this repo
# - installs additional python packages for modules
# - checks for any required external commands
# - sets up directory structure in ~/data

# cd to this directory
BASE_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")" || exit $?
readonly BASE_DIR
cd "${BASE_DIR}" || exit 1

# function to verify an external command is installed
havecmd() {
	local BINARY ERRMSG script_name
	script_name='HPI'
	# error if first argument isn't provided
	BINARY="${1:?Must provide command to check}"
	# the commend exists, exit with 0 (success!)
	if command -v "${BINARY}" >/dev/null 2>&1; then
		return 0
	else
		# construct error message
		ERRMSG="'${script_name}' requires '${BINARY}', could not find that on your \$PATH"
		if [[ -n "$2" ]]; then
			ERRMSG="$ERRMSG. $2"
		fi
		printf '%s\n' "$ERRMSG" 1>&2
		return 1
	fi
}

maybe_boxes() {
	# Print a fancy box, if boxes is installed
	# http://boxes.thomasjensen.com/
	if havecmd boxes >/dev/null 2>&1; then
		boxes -dshell -pv1h2
	else
		cat
	fi
}

clone_if_not_exists() {
	if [[ ! -d "$2" ]]; then
		git clone "$1" "$2" || return $?
	fi
}

pipm() {
	python3 -m pip "$@"
}

pip_install() {
	pipm install --user "$@"
}

setup_fork() {
	local FORK_ABBREV FORK_URL UPSTREAM_URL FORK_TARGET
	echo 'Setting up upstream fork...' | maybe_boxes

	# the name of my fork close to karlicoss/HPI, since HPI is this repo
	FORK_ABBREV='HPI-fork'

	UPSTREAM_URL='https://github.com/karlicoss/HPI'
	FORK_URL="https://github.com/seanbreckenridge/${FORK_ABBREV}"

	FORK_TARGET="$(realpath "../${FORK_ABBREV}")"

	# clone my fork one level up from here if it doesnt exist
	if [[ ! -e "${FORK_TARGET}" ]]; then
		git clone "${FORK_URL}" "${FORK_TARGET}"
		cd "${FORK_TARGET}" || return $?
		git remote add upstream "${UPSTREAM_URL}"
	else
		echo "Path already exists, skipping clone..."
	fi

	# install my fork of upstream
	cd "${FORK_TARGET}" || return $?
	pip_install -e '.[optional]' || return $?

	# cd back to here, to install this
	cd "${BASE_DIR}" || return $?
	pip_install -e '.' || return $?

	# make sure my repository appears before the upstream repo
	python3 -m reorder_editable reorder "${BASE_DIR}" "${FORK_TARGET}" || return $?
	python3 -m reorder_editable cat | maybe_boxes
}

setup_ghexport() {
	local URL TARGET
	# temporary (hopefully?) patch to use httpx instead of requests
	echo 'Setting up ghexport...'
	URL='https://github.com/seanbreckenridge/ghexport'
	TARGET="${REPOS:?Repos environment variable is not set}/ghexport"
	pip_install httpx
	clone_if_not_exists "$URL" "$TARGET"
	cd "$TARGET" || return $?
	git submodule update --init
	pip_install .
}

# install dependencies (with pip) for this module
# this works by traversing the AST/looking for
# a 'REQUIRES' global variable in the
# corresponding file
hpi_module() {
	hpi module install --user "$@"
}

module_dependencies() {
	echo "Installing module dependencies" | maybe_boxes
	# no my.github.gdpr because I install deps manually
	(setup_ghexport) || return $?
	hpi_module my.reddit || return $?
	hpi_module my.pdfs || return $?
	hpi_module my.window_watcher || return $?
	hpi_module my.smscalls || return $?
	hpi_module my.browsing || return $?
	hpi_module my.discord || return $?
	hpi_module my.body || return $?
	hpi_module my.google || return $?
	hpi_module my.time.tz.via_location || return $?
	hpi_module my.coding.commits || return $?
	hpi_module my.todotxt || return $?
	hpi_module my.location.ip || return $?
	hpi_module my.location.gpslogger || return $?
	hpi_module my.chess || return $?
	hpi_module my.mpv || return $?
	hpi_module my.league || return $?
	hpi_module my.trakt || return $?
	# other requirements needed in general/not specifically for a module
	pip_install -U -r ./requirements.txt || return $?
}

verify_personal_python_packages() {
	# some python packages I install manually as they're
	# pretty personal/require extensive configuration
	# here, just try and import them -- that shouldn't fail
	# https://github.com/seanbreckenridge/mint
	# https://github.com/seanbreckenridge/albums
	python3 -c "import nextalbums, budget" || return $?
}

setup_data_dir() {
	local DATA_PREFIX="${HPIDATA:-${HOME}/data}"
	local -a directories
	directories=(
		'phone/ttally'
		'doctor'
		'github/gdpr'
		'github/ghexport'
		'zsh_history'
		'bash_history'
		'rexport'
		'pushshift'
		'todotxt'
		'newsboat'
		'browsing'
		'mpv'
		'blizzard'
		'facebook_gdpr'
		'ipython'
		'old_forums'
		'ttt'
		'phone/ttt'
		'window_watcher'
		'google_takeout'
		'spotify'
		'apple'
		'discord'
		'league_of_legends'
		'chess'
		'trakt'
	)

	echo 'Setting up directories in ~/data' | maybe_boxes
	for dir in "${directories[@]}"; do
		ddir="${DATA_PREFIX}/${dir}"
		if [[ ! -d "${ddir}" ]]; then
			mkdir -p "${ddir}"
		fi
	done
}

required_commands() {
	# ordered from most likely to least likely
	echo 'Checking if required commands are installed...' | maybe_boxes
	havecmd curl || return $?
	havecmd git || return $?
	havecmd python3 || return $?
	havecmd fd 'Required for the my.coding.commits module' || return $?
}

optional_commands() {
	echo 'Checking if optional commands are installed...' | maybe_boxes
	havecmd evry "To handle background tasks; install from https://github.com/seanbreckenridge/evry" || return $?
	havecmd bgproc "For background tasks; install from https://github.com/seanbreckenridge/bgproc" || return $?
	havecmd wait-for-internet "To verify I have internet; install from https://github.com/seanbreckenridge/wait-for-internet" || return $?
	havecmd mispipe 'part of the moreutils package' || return $?
}

install_dependencies() {
	echo 'Installing dependencies...' | maybe_boxes
	# install arctee, needed for jobs
	havecmd arctee || pip_install 'git+https://github.com/karlicoss/arctee' || return $?
	havecmd reorder_editable || pip_install 'git+https://github.com/seanbreckenridge/reorder_editable' || return $?
}

prompt_if_fails() {
	printf "Command failed... Hit Enter to continue, Ctrl+C to exit"
	read -r
}

main() {
	required_commands || prompt_if_fails || return $?
	optional_commands || prompt_if_fails || return $?
	havecmd wait-for-internet >/dev/null 2>&1 && wait-for-internet --text "waiting for internet..."
	setup_data_dir || prompt_if_fails || return $?
	install_dependencies || prompt_if_fails || return $?
	(setup_fork) || prompt_if_fails || return $?
	module_dependencies || prompt_if_fails || return $?
	verify_personal_python_packages || prompt_if_fails || return $?
}

main "$@" || exit $?
