#!/bin/bash

# isnt needed that often, is only used so that backups exist
# otherwise, the zsh DAL reads from $ZDOTDIR/zsh_hist_file_name
# (set in ~/.config/my/my/__init__.py)
evry 1 month -backup_zsh_history && {
	readonly BACKUP_DIR="${HOME}/data/zsh_history"
	readonly ZSH_HIST_FILE="${ZDOTDIR:?ZDOTDIR environment variable not set}/.zsh_history"
	printlog "zsh_history:Backing up zsh history..."
	arctree "${BACKUP_DIR}/{utcnow}.zsh" -- cat "$ZSH_HIST_FILE"
}
