#!/usr/bin/env bash
# helper script to locate the backup
# directory while on an operating system

set -u

declare DIRNAME BACKUP_DIR
DIRNAME="${1:?Need to pass a directory name}" # e.g. zsh_history, browsing

# on my computer, I use syncthing to sync
# the ~/data directory back and forth across
# my computers
#
# however, that directory can get pretty big,
# so I'd rather not sync it to my phone
# There, I sync a subset; ~/data/phone/ instead
BACKUP_DIR="${HPIDATA}"
if [[ "${ON_OS}" == 'android' ]]; then
	BACKUP_DIR="${HPIDATA}/phone"
fi
BACKUP_DIR="${BACKUP_DIR}/${DIRNAME}"
mkdir -p "${BACKUP_DIR}"
printf '%s\n' "${BACKUP_DIR}"
