#!/usr/bin/env python3

"""
Copies the database into memory using
sqlite_copy_and_open, and then to a file
"""


import os

import click
import sqlite3

from my.core.sqlite import sqlite_copy_and_open


@click.command()
@click.argument("EXISTING_DB", type=click.Path(exists=True))
@click.argument("BACKUP_DB", type=click.Path())
def main(existing_db: str, backup_db: str) -> None:
    assert os.path.exists(existing_db), f"Source {existing_db} does not exist"
    memcopy = sqlite_copy_and_open(existing_db)
    backup_conn = sqlite3.connect(backup_db)
    memcopy.backup(backup_conn)
    memcopy.close()
    backup_conn.close()
    click.echo(f"Backed up '{existing_db}' to '{backup_db}'")


if __name__ == "__main__":
    main()
