#!/usr/bin/env python3

"""
Print any shows/movies I've watched which I haven't rated
"""

from my.trakt.export import ratings, history, D


def main() -> None:
    rat = {r.media_data.url: r for r in ratings()}

    printed: set[str] = set()
    for hst in history():
        m = hst.media_data
        if isinstance(m, D.Movie):
            u = m.url
            if u not in rat and u not in printed:
                print(u)
                printed.add(u)
        elif isinstance(m, D.Episode):
            u = m.show.url
            if u not in rat and u not in printed:
                print(u)
                printed.add(u)


if __name__ == "__main__":
    main()
