#!/usr/bin/env bash
# print the most common netlocs from my browsing history
# ./history_common 500 to print the top 500

set -e
set -o pipefail

declare COUNT
COUNT="${1:-250}"

exec hpi query -s 'my.browser.export.history' |
	jq -r '.url' |
	cut -d"/" -f-3 |
	sed -e 's/www\.//' -e 's|https://||' -e 's|http://||' |
	sort |
	uniq -c |
	sort -n | tail -n "${COUNT}"
