#!/usr/bin/env bash
# fuzzy search all my history (with descriptions, to help match what I'm looking for)

set -e
set -o pipefail

# awk: removes duplicates
# additional jq after you pick with fzf removes quotes (-r)

exec hpi query -s my.browsing.history |
	jq '"\(.url)|\(.metadata.description)"' |
	awk '!seen[$0]++' |
	fzf +m --tac |
	jq -r |
	cut -d"|" -f1
