#!/usr/bin/env python3
# script to check differences between mistletoe
# and pandoc 'markdown -> HTML' generation
# https://github.com/karlicoss/promnesia/issues/233

import shutil
from subprocess import run, PIPE

import click
from my.github.all import events
from mistletoe import HTMLRenderer, Document


def pandoc_convert(text: str) -> str:
    pandoc_path = shutil.which("pandoc")
    assert pandoc_path is not None
    r = run(
        [pandoc_path, "-f", "markdown", "-t", "html", "--wrap=none"],
        check=True,
        input=text.encode("utf8"),
        stdout=PIPE,
    )
    res = r.stdout.decode("utf8")
    return res.strip()


renderer = HTMLRenderer()


def mistletoe_convert(text: str) -> str:
    return renderer.render(Document(text)).strip()


def _no_space_compare(one: str, two: str) -> bool:
    return "".join(one.split()).strip() == "".join(two.split()).strip()


def main() -> None:
    for e in events():
        if isinstance(e, Exception):
            continue
        ctx = e.body
        if ctx is None:
            continue
        p = pandoc_convert(ctx)
        m = mistletoe_convert(ctx)
        if _no_space_compare(p, m):
            continue
        print("PANDOC:")
        print(p)
        print("---")
        print("MISTLETOE:")
        print(m)
        print("------")
        input()
        click.clear()
        print("\n\n\n\n\n")


# just use github markdown as input
if __name__ == "__main__":
    main()
