#!/bin/bash

URL='https://github.com/karlicoss/ghexport'
TARGET="${REPOS:?Repos environment variable is not set}/ghexport"

clone_if_not_exists "$URL" "$TARGET"
cd "$TARGET" || exit $?
git submodule update --init
python -m pip install -e .
