#!/bin/bash

URL='https://github.com/karlicoss/rexport/'
TARGET="${REPOS:?Repos environment variable is not set}/rexport"

clone_if_not_exists "$URL" "$TARGET"
cd "$TARGET" || exit $?
pip3 install -r requirements.txt
