#!/bin/bash -uex
# makes sure that data directories at ~/data exist

readonly DATA_PREFIX="${HOME}/data"

declare -a directories
directories=(
	'body'
	'doctor'
	'github/gdpr'
	'github/ghexport'
	'zsh_history'
	'rexport'
	'todotxt'
	'rss'
	'firefox'
	'mpv'
	'blizzard'
	'facebook_gdpr'
	'rps_comments'
	'ipython'
	'old_forums'
	'ttt'
	'window_watcher'
	'google_takeout'
	'spotify'
	'apple'
	'discord'
	'league_of_legends'
)

declare -a files
files=(
	'body/weight.json'
	'body/shower.json'
	'body/water.json'
)

for dir in "${directories[@]}"; do
	ddir="${DATA_PREFIX}/${dir}"
	if [[ ! -d "${ddir}" ]]; then
		mkdir -p "${ddir}"
	fi
done

for file in "${files[@]}"; do
	dfile="${DATA_PREFIX}/${file}"
	if [[ ! -e "${dfile}" ]]; then
		touch "${dfile}"
	fi
done
