#!/bin/bash

declare -a TAKEOUT_ZIPS=()
declare GOOGLE_DRIVE_TAKEOUT_DIR
GOOGLE_DRIVE_TAKEOUT_DIR="${1:?Provide Google Drive Takeout directory as first argument}"

# read all takeouts into array
while read -r -d $'\0' zipped_takeout; do
	TAKEOUT_ZIPS+=("$zipped_takeout")
done < <(find "${GOOGLE_DRIVE_TAKEOUT_DIR}" -type f -name "*.zip" -print0)

if [[ "${#TAKEOUT_ZIPS}" == 0 ]]; then
	echo "No takeouts found at ${GOOGLE_DRIVE_TAKEOUT_DIR}, exiting..."
	exit 1
fi

for takeout in "${TAKEOUT_ZIPS[@]}"; do
	google_takeout_parser move --from "${takeout}" --to-dir "${HPIDATA}/google_takeout" --no-extract
done
