#!/bin/bash
# backup firefox/chrome browsing history

save_database() {
	local BROWSER="${1:?Must provide browser to backup}"
	browserexport save -b "${BROWSER}" --to "$(python3 -m my.utils.backup_to browsing)" || send-error "browserexport: failed to backup ${BROWSER} database..."
}

evry 1 week -backup_browser_history && {
	printlog "browserexport:backing up shared history databases..."
	save_database firefox
	save_database chrome
}
