#!/bin/bash
# backup firefox/chrome browsing history

save_database() {
	local BROWSER="${1:?Must provide browser to backup}"
	local -r BACKUP_DIR="${HPIDATA}/browsing/"
	browserexport save -b "${BROWSER}" --to "${BACKUP_DIR}" || send-error "browserexport: failed to backup ${BROWSER} database..."
}

evry 1 week -backup_browser_history && {
	printlog "browserexport:backing up shared history databases..."
	save_database firefox
	save_database chrome
}
