#!/bin/bash
# remind me to log my weight

set -o pipefail

evry 3 hours -checkbody && {
	printlog "checkbody:checking last time I logged my weight..."
	# cross platform script that sends notifications
	# https://sean.fish/d/cross-platform/notify
	LOGCOUNT="$(hpi query --recent 1w my.body.weight | jq length)" || send-error "check_body: hpi query failed"
	[[ "${LOGCOUNT}" == '0' ]] && notify "havent updated weight in more than a week!"
}
