#!/bin/bash -uex
# makes sure that data directories at ~/data exist

readonly DATA_PREFIX="${HOME}/data"

declare -a directories
directories=(
	'github/gdpr'
	'github/ghexport'
	'zsh_history'
	'rexport'
	'todotxt'
	'rss'
	'firefox/dbs'
	'mpv'
	'blizzard'
	'facebook_gdpr'
	'league_of_legends'
	'rps_comments'
	'ipython'
)
declare -a files
files=(
	'weight.json'
)

for dir in "${directories[@]}"; do
	ddir="${DATA_PREFIX}/${dir}"
	if [[ ! -d "${ddir}" ]]; then
		mkdir -p "${ddir}"
	fi
done

for file in "${files[@]}"; do
	dfile="${DATA_PREFIX}/${dir}"
	if [[ ! -e "${dfile}" ]]; then
		touch "${dfile}"
	fi
done
