#!/bin/bash -e

BASE_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"
cd "$BASE_DIR"

# the name of my fork close to karlicoss/HPI, since HPI is this repo
FORK_ABBREV='HPI-to-master'

UPSTREAM_URL='https://github.com/karlicoss/HPI'
FORK_URL="https://github.com/seanbreckenridge/${FORK_ABBREV}"

FORK_TARGET="$(realpath "../${FORK_ABBREV}")"

# clone my fork one level up from here if it doesnt exist
set -x
if [[ ! -e "${FORK_TARGET}" ]]; then
	git clone "${FORK_URL}" "${FORK_TARGET}"
	cd "${FORK_TARGET}"
	git remote add upstream "${UPSTREAM_URL}"
	pip install -e "${FORK_TARGET}"
else
	echo "Path already exists, skipping setting up fork..."
fi

# cd back to here, to pip install this
cd "${BASE_DIR}" || exit $?
pip install -e .
# TODO: re-order easy-install.path?

# we're still in $BASE_DIR, specify relative path from there
./setup/setup_deps
