#!/bin/bash -uex
# makes sure that data directories at ~/data exist

readonly DATA_PREFIX="${HOME}/data"

declare -a directories
directories=(
	'tupletally'
	'doctor'
	'github/gdpr'
	'github/ghexport'
	'zsh_history'
	'bash_history'
	'rexport'
	'todotxt'
	'newsboat'
	'firefox'
	'mpv'
	'blizzard'
	'facebook_gdpr'
	'rps_comments'
	'ipython'
	'old_forums'
	'ttt'
	'window_watcher'
	'google_takeout'
	'spotify'
	'apple'
	'discord'
	'league_of_legends'
	'chessdotcom'
	'trakt'
	'albums'
)

for dir in "${directories[@]}"; do
	ddir="${DATA_PREFIX}/${dir}"
	if [[ ! -d "${ddir}" ]]; then
		mkdir -p "${ddir}"
	fi
done
