#!/bin/bash
# backup current messages (imessage) database

evry 1 week -backup_imessages && {
	readonly MESSAGES_DB="${HOME}/Library/Messages/chat.db"
	printlog "imessage:backing up history database..."
	# https://github.com/seanbreckenridge/sqlite_backup
	sqlite_backup "${MESSAGES_DB}" "$(python3 -m my.utils.backup_to imessage)/$(date +'%s').sqlite" || send-error 'imessage: failed to backup database'
}
